<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSufzlb1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSufzlb1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSufzlb1.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSufzlb1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSufzlb1\appDevDebugProjectContainer([
    'container.build_hash' => 'Sufzlb1',
    'container.build_id' => 'db1010f1',
    'container.build_time' => 1637206087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSufzlb1');
